coverage:
  status:
    project: off
    patch: off

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: extra-data-types
      paths:
        - src/
      statuses:
        - type: project
          target: 100%
          threshold: 1%