name: Auto Test by PR

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          pr-emoji: "+1, heart"
      - name: Install modules
        run: npm install
      - name: PR build
        run: npm run build-pr
      - name: Run tests
        run: npm run test
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
