name: Auto-approve PR

on:
  pull_request:
    types: [opened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - name: Auto approve pull request
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_PR_TEST_APPROVE }}
      run: |
        curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
        -d '{"event":"APPROVE"}'
