name: auto-test-by-PR

on: 
  pull_request:
    branches: 
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          pr-emoji: '+1, heart'
      - name: Install modules
        run: npm install
      - name: PR check
        run: npm run pr-check
      - name: Run tests
        run: npm run test

