name: PR Welcome

on: 
  pull_request:
    branches: 
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: npm test
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          pr-emoji: '+1, heart'
